const GET_USERS_SAGA = 'GET_USERS_SAGA';
const SET_USERS = 'SET_USERS';
const GET_POST_COMPONENT_DATA = 'GET_POST_COMPONENT_DATA';

export {  //eslint-disable-line
  GET_USERS_SAGA,
  SET_USERS,
  GET_POST_COMPONENT_DATA
};
